#!/bin/bash

# Read stdin and display it as a web page

fout=/tmp/webcat`date "+%H-%M-%S"`.html

echo "<!DOCTYPE html><html>" > $fout
echo "<head><title>$@</title></head>" >> $fout
echo "<body style='font-family:sans-serif;'>" >> $fout
echo "  <div style='width: 800px; margin: 0 auto'>" >> $fout
echo "    <h1>"$@"</h1>" >> $fout
echo "      <div class='content'>" >> $fout

cat | Markdown.pl >> $fout

echo "      </div>"  >> $fout
echo "    </div>"  >> $fout
echo "  </body>" >> $fout
echo "</html>" >> $fout

open $fout